# Generated by Django 3.2.5 on 2021-07-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeCryptoCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=150)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('closed_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('closed_at', models.DateTimeField()),
            ],
        ),
    ]
